name: Build site and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuring build Environment
      run: |
        sudo apt-get update
        python -m pip install -U pip

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Installing dependencies
      run: |
        python -m pip install -r docs/requirements.txt
        gem install jekyll jekyll-remote-theme jekyll-sass-converter

    - name: Build all example pages
      run: |
        cd examples/abort-reload && npm install && npm run build && cd ../..
        cd examples/cache-usage && npm install && npm run build && cd ../..
        cd examples/chrome-extension-webgpu-service-worker && npm install && npm run build && cd ../..
        cd examples/chrome-extension && npm install && npm run build && cd ../..
        cd examples/embeddings && npm install && npm run build && cd ../..
        cd examples/function-calling/function-calling-manual && npm install && npm run build && cd ../../..
        cd examples/function-calling/function-calling-openai && npm install && npm run build && cd ../../..
        cd examples/get-started-web-worker && npm install && npm run build && cd ../..
        cd examples/get-started && npm install && npm run build && cd ../..
        cd examples/json-mode && npm install && npm run build && cd ../..
        cd examples/json-schema && npm install && npm run build && cd ../..
        cd examples/logit-processor && npm install && npm run build && cd ../..
        cd examples/multi-models && npm install && npm run build && cd ../..
        cd examples/multi-round-chat && npm install && npm run build && cd ../..
        cd examples/next-simple-chat && npm install && npm run build && cd ../..
        cd examples/seed-to-reproduce && npm install && npm run build && cd ../..
        cd examples/service-worker && npm install && npm run build && cd ../..
        cd examples/simple-chat-js && npm install && npm run build && cd ../..
        cd examples/simple-chat-ts && npm install && npm run build && cd ../..
        cd examples/simple-chat-upload && npm install && npm run build && cd ../..
        cd examples/streaming && npm install && npm run build && cd ../..
        cd examples/text-completion && npm install && npm run build && cd ../..
        cd examples/vision-model && npm install && npm run build && cd ../..

    - name: Build and deploy site
      if: github.ref == 'refs/heads/main'
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.MLC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git config --global user.email "mlc-gh-actions-bot@nomail"
        git config --global user.name "mlc-gh-actions-bot"

        ./scripts/gh_deploy_site.sh
